############### PLS-PM Analysis #################

# PLS-PM models are computed using plspm package developed by Gaston Sanchez.
# For details on how to configure the model please refer to its documentation: 
# https://www.gastonsanchez.com/PLS_Path_Modeling_with_R.pdf

####### 1. Config and Data Import ####### 

# Set the working directory and load required libraries.
setwd("xxx")

# Upload required packages
library(readxl) # Import Excel file
library(plspm)  # Partial Least Square Path Modelling
library(openxlsx) # Output Excel files

# Data Import
Data <- read.csv('data/synthetic_ESCCOL_AMR_AMC_CEPH_2021.csv')
Name <- c("Outputs/ESCCOL_AMR_AMC_CEPH_2021")

####### 2. Data Pre-processing ####### 

# Remove country code column.
Data1 <- Data[, -c(1, 10)]
summary(Data1)
# Remove countries with missing values.
Data2 <- Data[rowSums(is.na(Data)) == 0, ]
summary(Data2)

####### 3.Partial Least Squares Path Modeling Estimation ####### 

####### 3.1. PLS-PM Full Model  ####### 

### 3.1.1. Model Specification (Full Model, all relationships considered)

# Define the path model for latent variables (AMCa, AMCh, AMRa, AMRh).
AMCa <- c(0, 0, 0, 0)  # No path to other latent variables from AMCa
AMCh <- c(0, 0, 0, 0)  # No path to other latent variables from AMCh
AMRa <- c(1, 0, 0, 0)  # AMRa is related to the first latent variable (AMCa)
AMRh <- c(1, 1, 1, 0)  # AMRh is related to AMCa, AMCh, and AMRa

# Create the path matrix 'sat_path1' with indicator definitions
sat_path1 <- rbind(AMCa, AMCh, AMRa, AMRh)

# Set column names for clarity
colnames(sat_path1) <- rownames(sat_path1)

# Validate the the inner structural model using the 'innerplot' function
innerplot(sat_path1, arr.pos = 0.8)

### 3.1.2. Definition of Latent Variables from Manifest Variables 

# Define the variables associated with latent variables.
sat_blocks1 <- list(3, 5:6, 7:8, 9)

# Note: In this example, cephalosporin consumption is not recorded in poultry, 
#       so the 4th column containing zero values is omitted.
#       For any other class, the first latent variable corresponds to 3:4

### 3.1.3. PLS-PM Model Estimation

# Estimate the PLS-PM model using the 'plspm' function.
satpls1 <- plspm(Data2, sat_path1, blocks = sat_blocks1, 
                 modes = rep("B", 4), scheme = "path", scaled = TRUE, 
                 boot.val = TRUE, br = 200)
# Display a summary of the PLS-PM results
# Check which are the  significant paths to $AMRh (Pr(>|t|)<0.05) for selection
# of paths in next simplified model
summary(satpls1)

# Optional: Export results to Excel or PDF
# These output files are informative and customizable. The multivariate analyses 
# figures found in JIACRA IV have been done outside the R software, but including 
# the information generated by the models from this script

# Define the path file name 
output_file <- paste(Name, "_Complete_Plspm.xlsx", sep = "")

# Create a workbook object
wb <- createWorkbook()

# Add the Excel sheets
addWorksheet(wb, "Inner_AMRa")
writeData(wb, sheet = 1, x = satpls1$inner_model$AMRa)

addWorksheet(wb, "Inner_AMRh")
writeData(wb, sheet = 2, x = satpls1$inner_model$AMRh)

addWorksheet(wb, "Inner_R2")
writeData(wb, sheet = 3, x = satpls1$boot$rsq)

addWorksheet(wb, "Loadings")
writeData(wb, sheet = 4, x = satpls1$boot$loadings)

# Save the workbook to the specified Excel file
saveWorkbook(wb, output_file, overwrite = TRUE)

# Plot the inner structural model
innerplot(satpls1,  arr.pos = 0.7, arr.tcol = 'black')
dev.copy(pdf, paste(Name, "_Complete_Inner", ".pdf", sep = ""))
dev.off()
# Plot the outer structural model
outerplot(satpls1, what = "loadings", arr.pos = 0.7, arr.tcol = 'black')
dev.copy(pdf, paste(Name, "_Complete_Outer", ".pdf", sep=""))
dev.off()

####### 3.2 PLS.PM Simplified Model ####### 
# (Suppressing Non-Significant Path Between AMCa and AMRh)

### 3.2.1 Model Specification (Simplified Model)

# Define the path model for latent variables (AMCa, AMCh, AMRa, AMRh).
AMCa <- c(0, 0, 0, 0)  # No path to other latent variables from AMCa
AMCh <- c(0, 0, 0, 0)  # No path to other latent variables from AMCh
AMRa <- c(1, 0, 0, 0)  # AMRa is related to the first latent variable (AMCa)
AMRh <- c(0, 1, 1, 0)  # AMRh is related to AMCh and AMRa

# Create the path matrix 'sat_path2' with indicator definitions
sat_path2 <- rbind(AMCa, AMCh, AMRa, AMRh)

# Set column names for clarity
colnames(sat_path2) <- rownames(sat_path2)

# Plot the inner structural model using the 'innerplot' function
innerplot(sat_path2,  arr.pos = 0.8)

### 3.2.2. Definition of Latent Variables from Manifest Variables

# Here, the variables from the different columns are associated with the different latent variables.
sat_blocks2 <- list(3, 5:6, 7:8, 9)

# Note: In this example, cephalosporin consumption is not recorded in poultry, 
#       so the 4th column containing zero values is omitted.
#       For any other class, the first latent variable corresponds to 3:4

### 3.2.3. PLS-PM Simplified Model Estimation
satpls2 <- plspm(Data2, sat_path2, blocks = sat_blocks2, modes = rep("B", 4), 
                 scheme = "path", scaled = TRUE, boot.val = TRUE, br = 200)

# Display a summary of the PLS-PM results
# Check which are the  significant paths to $AMRh (Pr(>|t|)<0.05) for selection
# of paths in next final model
summary(satpls2)  

# Optional: Export results to Excel or PDF
# These files are informative, the multivariate analyses figures found in
# JIACRA IV have been done outside R, including the information from these files

# Define the path file name 
output_file <- paste(Name, "_Simplified_Plspm.xlsx", sep = "")
  
# Create a workbook object
wb <- createWorkbook()
  
# Add the Excel sheets
addWorksheet(wb, "Inner_AMRa")
writeData(wb, sheet = 1, x = satpls2$inner_model$AMRa)
  
addWorksheet(wb, "Inner_AMRh")
writeData(wb, sheet = 2, x = satpls2$inner_model$AMRh)

addWorksheet(wb, "Inner_R2")
writeData(wb, sheet = 3, x = satpls2$boot$rsq)

addWorksheet(wb, "Loadings")
writeData(wb, sheet = 4, x = satpls2$boot$loadings)

# Save the workbook to the specified Excel file
saveWorkbook(wb, output_file, overwrite = TRUE)
 
# Plot the inner structural model
innerplot(satpls2,  arr.pos = 0.7, arr.tcol = 'black')
dev.copy(pdf, paste(Name, "_Simplified_Inner", ".pdf", sep = ""))
dev.off()

# Plot the outer structural model
outerplot(satpls2, what = "loadings", arr.pos = 0.7, arr.tcol = 'black')
dev.copy(pdf, paste(Name, "_Simplified_Outer", ".pdf", sep=""))
dev.off()


####### 3.3. PLS-PM Final Model (Only Significant Path) ####### 

### 3.1.3, Model Specification
# As animal data are no longer used in the model, a new specification of latent variables relationships is done below with only two latent variables.

AMCh <- c(0, 0)  # No path to other latent variables from AMCh
AMRh <- c(1, 0)  # AMRh is related to consumption in humans

# Create the path matrix 'sat_path3ter' with indicator definitions
sat_path3ter <- rbind(AMCh, AMRh)

# Set column names for clarity
colnames(sat_path3ter) <- rownames(sat_path3ter)

# Plot the inner structural model using the 'innerplot' function
innerplot(sat_path3ter,  arr.pos = 0.8)

# 3.1.2. Latent Variables Definition
sat_blocks3ter <- list(5:6, 9)

# 3.1.3. PLS-PM Final Model Estimation
satpls3ter <- plspm(Data2, sat_path3ter, blocks = sat_blocks3ter, 
                    modes = rep("B", 2), scheme = "path", scaled = TRUE, 
                    boot.val = TRUE, br = 200)
# Display a summary of the PLS-PM results
summary(satpls3ter)

# The results derived from this final model using synthetic data correspond to 
# what is reported in the JIACRA IV report. The only significant relationship 
# retained in the final model of AMRh to CEPH was the strong direct impact of
# AMCh (Beta = 0.86 [0.76-0.96]; Rsquare = 0.74 [0.64-0.84])

# Optional: Export results to Excel or PDF
# These files are informative, the multivariate analyses figures found in
# JIACRA IV have been done outside R, including the information from these files

# Define the file path for the Excel file
output_file <- paste(Name, "_Final_Plspm.xlsx", sep = "")

# Create an Excel workbook object
wb <- createWorkbook()

# Add sheets to the workbook
addWorksheet(wb, "Inner_AMRh")
writeData(wb, sheet = 1, x = satpls3ter$inner_model$AMRh)

addWorksheet(wb, "Inner_R2")
writeData(wb, sheet = 2, x = satpls3ter$boot$rsq)

addWorksheet(wb, "Loadings")
writeData(wb, sheet = 3, x = satpls3ter$boot$loadings)

# Save the workbook to the specified Excel file
saveWorkbook(wb, output_file, overwrite = TRUE)

# Plot the inner structural model
innerplot(satpls3ter,  arr.pos = 0.7, arr.tcol = 'black')
dev.copy(pdf, paste(Name, "_Final_Inner", ".pdf", sep = ""))
dev.off()

# Plot the outer structural model
outerplot(satpls3ter, what = "loadings", arr.pos = 0.7, arr.tcol = 'black')
dev.copy(pdf, paste(Name, "_Final_Outer", ".pdf", sep=""))
dev.off()

